### ISSUE TITLE
Plugin error not telling me where the error was

### ISSUE THREAD

**Issue by saxobroko** [Tom-Bonnike/netlify-plugin-inline-critical-css#18]
I know the error has something to do with my css but, i don't know where.

```
────────────────────────────────────────────────────────────────
  Plugin "netlify-plugin-inline-critical-css" failed
────────────────────────────────────────────────────────────────
​
  Error message
  CssSyntaxError: Failed to inline critical CSS.
  <css input>:1:1971: Missed semicolon
​
  Plugin details
  Package:        netlify-plugin-inline-critical-css
  Version:        1.2.0
  Repository:     git+https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css.git
  npm link:       https://www.npmjs.com/package/netlify-plugin-inline-critical-css
  Report issues:  https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues
​
  Error location
  In "onPostBuild" event in "netlify-plugin-inline-critical-css" from Netlify app
      at Input.error (/.netlify/plugins/node_modules/postcss/lib/input.js:128:16)
      at Parser.checkMissedSemicolon (/.netlify/plugins/node_modules/postcss/lib/parser.js:601:22)
      at Parser.decl (/.netlify/plugins/node_modules/postcss/lib/parser.js:284:46)
      at Parser.other (/.netlify/plugins/node_modules/postcss/lib/parser.js:164:12)
      at Parser.parse (/.netlify/plugins/node_modules/postcss/lib/parser.js:75:16)
      at Function.parse (/.netlify/plugins/node_modules/postcss/lib/parse.js:17:12)
      at getCssMapping (/.netlify/plugins/node_modules/postcss-discard/index.js:88:19)
      at /.netlify/plugins/node_modules/postcss-discard/index.js:169:21
      at creator (/.netlify/plugins/node_modules/postcss/lib/postcss.js:133:35)
      at extractCss (/.netlify/plugins/node_modules/inline-critical/src/css.js:42:20)
​
```

**Comment by Tom-Bonnike** [comment]
Not too sure either, the CSS seems to be minified otherwise the error would point to the correct line. Can you maybe try disabling any minification so you can find which line it is? Otherwise you could try running [stylelint](https://github.com/stylelint/stylelint) on your source files.
